# Quality Assurance

## Quality Assurance/Quality Control (QA/QC) Grounding

According to the [Water Boards Quality Assurance/Quality Control Website](https://www.waterboards.ca.gov/water_issues/programs/quality_assurance/):

> Quality assurance and quality control are components of a quality system. A quality system is a structured system that describes the policies and procedures for ensuring that work processes, products, or services satisfy the user's specifications and expectations. A quality system is the means by which an organization manages its quality aspects. These aspects are Project Management, Data Generation and Acquisition, and Assessment and Oversight.

**Quality Assurance (QA)** involves an integrated system of management activities that involves planning, implementation, documentation, assessment, reporting, and quality improvement to ensure that a process, item, or service is of the type and quality required for the project needs.

**Quality Control (QC)** involves a system of technical activities that measures the attributes and performance of a process, item, or service against defined standards to verify that they meet the stated requirements established by the customer. QC also involves analytical frequency requirements and control limits.

## QA/QC with an Equity Lens

**Setting up your QA system with an equity lens** requires thinking through the systems that are already in place and assessing the extent to which they are supporting the advancement of equity objectives associated with your project. Consider reviewing the pages associated with the aforementioned QA activities to see if your systems are on track:

-   Planning: [Planning](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html), [Data Preparation](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/prep.html)
-   Implementation: [Data Collection](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/collection.html), [Data Processing](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/process.html), [Data Analysis](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/analysis.html), [Data Visualization](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/vis.html), [Preservation & Storage](https://cawaterboarddatacenter.github.io/equity-data-handbook/store.html)
-   Documentation: [Describe (aka Documentation)](https://cawaterboarddatacenter.github.io/equity-data-handbook/documentation.html)
-   Assessment: [Discover & Integrate (aka Evaluation)](https://cawaterboarddatacenter.github.io/equity-data-handbook/eval.html)
-   Reporting: [Data Sharing](https://cawaterboarddatacenter.github.io/equity-data-handbook/share.html)
-   Quality Improvement: If some or all of your QA systems are not in support of your equity objectives, think through what changes you/your team can make to your process NOW to better operationalize equity.

**Setting up your QC system with an equity lens** requires thinking through how we're measuring quality/performance and the standards we're using to assess quality.

-   How do our current performance measures help us assess the extent to which we're meeting project objectives?

-   Do any of our current performance measures make it difficult for us to achieve our equity objectives? If so, how might we modify or eliminate them?

-   What additional performance measures would better help us assess the extent to which this data-intensive project is meeting the project's equity objectives?

-   Do the standards, thresholds, or limits we're using align with the needs of those facing inequity or disparities - are or likely will be affected by a policy, program, or process? If not, how might we modify the them to better align with those needs?

**From the data science perspective, conducting QA/QC of the data requires** checking values of the dataset against the aforementioned standards to understand the quality of the data.

-   Is the metadata and vocabulary associated with each dataset complete, easy to access, and simple enough to be understood by a variety of audiences?

-   If data is of insufficient quality and needs to be excluded from future steps - where and how will documentation summarize what measures/standards were used to make such determination and which data were excluded?

## **Resources**

-   [Water Boards QAQC Webpage](https://www.waterboards.ca.gov/water_issues/programs/quality_assurance/)
-   [SWAMP Bioaccumulation Monitoring Program Training Series](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring/training.html)
    -   Data Quality and Data Management - [Slides 67-80](https://drive.google.com/file/d/1ler3HO5B6M4_ywfuR00A621J6yLH2tGi/view) \| [Recording Part 3](https://www.youtube.com/watch?v=ZG_KPsQM55c&t=6920s)

    -   Quality Assurance & Quality Control - [Slides 5 - 38](https://drive.google.com/file/d/18HdaNwB0in1Z4L42B6Pvc-XWNq98RnLf/view?usp=sharing) \| [Recording Part 1](https://www.youtube.com/watch?v=W3nOeLxlDQc&t=220s)
