project:
  type: book

book:
  title: "User Manual for CA Water Board's Tribal Water Data Map"
  author: "CA Water Board's Office of Information Management and Analysis (OIMA)"
  date: "2023-08-24"
  search: true
  repo-url: https://github.com/CAWaterBoardDataCenter/swamp-manual
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
  
    - index.qmd
    - about-swamp.qmd
    
    - part: Culture
      chapters:
        - values.qmd
        - codeofconduct.qmd
        - expectations.qmd
        - development.qmd
    
    - part: Administrative goodies
      chapters: 
        - onboarding.qmd
        - travel.qmd
        - training.qmd
        - tech.qmd
        - procurement.qmd
        - offboarding.qmd
    
    - lifecycle.qmd
    - contacts.qmd
    - contribute.qmd
    - inspiration.qmd
    - references.qmd
    
  sidebar:
    style: "docked"
    logo: "images/swamp-iq-logos.png"
    # type: "light"
    # background: "#002151"
    # foreground: "light"
    border: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

# comments:
#   hypothesis: true