project:
  type: book

book:
  title: "Equity Data Handbook"
  author: "CA Water Board's Office of Information Management and Analysis (OIMA)"
  date: "2024-07-01"
  search: true
  repo-url: https://github.com/CAWaterBoardDataCenter/equity-data-handbook
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
  
    - index.qmd
    - background.qmd
    
    - part: Getting Started
      chapters:
        - get-started.qmd
        - best-practice.qmd
        - common-language.qmd
        
    - part: Plan & Prepare
      chapters:
        - plan.qmd
        - prep.qmd
        
    - part: Collect & Process
      chapters:
        - sources.qmd
        - surveys.qmd
        - limits.qmd

    - part: Assure & Analyze
      chapters:
        - analysis.qmd
        - vis.qmd
        - demographics.qmd
        - calenviroscreen.qmd
        - data-into-information.qmd
        - demographics-data.qmd
        
    - part: Preserve & Store
      chapters:
        - store.qmd
        
    - part: Publish & Share
      chapters:
        - share.qmd

    - part: Discover & Integrate
      chapters:
        - store.qmd
        
    - part: Describe
      chapters:
        - documentation.qmd
  
    - part: Use Cases
      chapters:
        - uc1.qmd
        - uc2_demographics.qmd
        
    - resources.qmd
    - inspo.qmd
    
  sidebar:
    style: "docked"
    logo: "images/WaterBoards_logo.png"
    # type: "light"
    # background: "#002151"
    # foreground: "light"
    border: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

# comments:
#   hypothesis: true