# Best Practices

-   Use the best available science while relying on current, generally accepted Agency procedures for conducting risk assessment and economic analysis.  

-   Use existing frameworks and data from other parts of the regulatory analysis, supplemented as appropriate.  

-   Be consistent with the basic assumptions underlying other parts of the analysis, such as using the same baseline and option scenarios.

-   Use the highest quality and most recent data available. Discuss the overall quality and main limitations of the data (e.g., completeness, accuracy, validation). 

-   Discuss available evidence of factors that may make population groups of concern more vulnerable to adverse effects (e.g., unique pathways; cumulative exposure from multiple stressors; and behavioral, biological, or environmental factors that increase susceptibility). 

-    Identify unique considerations for subsistence populations when relevant. 

-   Carefully select and justify the choice of a comparison population group.  

-   Carefully select and justify the choice of the geographic unit of analysis and discuss any particular challenges or aggregation issues related to the choice of spatial scale.

-   Analyze and compare effects in baseline and across policy scenarios to show differences in effects.

-   Present summary metrics for relevant population groups of concern as well as the comparison population group. 

-   When data allow, characterize the distribution of risks, exposures, or outcomes within each population group, instead of presenting only average effects. 

-   Disaggregate data to reveal important spatial differences (e.g., demographic information for each facility/place) when feasible and appropriate.

-   Discuss the severity and nature of the health consequences for which differences between population groups have been analyzed. 

-   Clearly describe data sources, assumptions, analytic techniques, and results. 

-   Discuss key sources of uncertainty or potential biases in the data (e.g., sample size, using proximity as a surrogate for exposure) and how they may influence results.

-   When possible, conduct sensitivity analysis for key assumptions or parameters that may affect findings. 

-   Make elements of Environmental Justice (EJ) assessments as straightforward and easy for the public to understand as possible. 

**Non-Inclusive Terms to Avoid:**

-   “Brown Bag” - The term “brown bag” has a historical connotation with creating an exclusive gathering that required attendees to have a lighter skin tone than a brown paper bag to participate and gain access.

    -   Alternatives: lunch in, lunch and learn

-   “Chief” - this term is used throughout the Water Boards to indicate positions and job titles.  This term is appropriated from the Indigenous Peoples of North America and should be avoided wherever possible.

    -   Alternatives: manager, lead, head

-   “Grandfathered in” - The American South created absurd voting requirements that targeted Black people and made it almost impossible to vote. The name for these requirements is the "Grandfather Clause." They wrote the Amendment in a way to imply the practice was not discriminatory. They created stringent new voter requirements such as literacy tests. These requirements did not apply to people who had voted before 1867. Slaves did not know they were free until June 19, 1865. However, slavery was abolished on January 1, 1863, making it nearly impossible for a person formally kept in captivity to be legally allowed to vote.

    -   Alternatives:  legacied, exempted, preapproved

-   “Master \_\_\_\_” - using the term Master to describe something that is the main or centralized source of information like a PowerPoint presentation or slide deck is inappropriate due to the connotations associated with slavery.

    -   Alternatives: primary, main

-   “White Paper” - while this term is widely used to describe an authoritative document, the term has historical implications that evoke negative associations especially with Tribes. 

    -   Alternatives: Issue paper, briefing document, prospectus
