# Meet the Team!

The development of the [Map](https://gispublic.waterboards.ca.gov/portal/home/item.html?id=a71c1841907240e1a4d896c8cf2302a8) and this User Manual has been a team effort from the start. Below is a list of team members within OIMA and tribal partners who have been integral to the development of these resources.

If you would like to join the Team, please email Anna Holder at: [anna.holder\@waterboards.ca.gov](mailto:anna.holder@waterboards.ca.gov).

## OIMA

| Name                                                 | Title                                             |
|-------------------------------------|-----------------------------------|
| [Anna Holder](mailto:anna.holder@waterboards.ca.gov) | Environmental Scientist & OIMA Tribal Coordinator |
| Leah Benton                                          | CivicSpark Fellow                                 |

## Tribal Partners

| Name           | Title                  | Affiliation                                                                                                              |
|-----------------|-----------------|---------------------------------------|
| Sarah Ryan     | Environmental Director | Big Valley Band of Pomo Indians, Environmental Protection Department ([Big Valley EPA](https://www.bvrancheria.com/epa)) |
| Meyo Marrufo   | Environmental Director | Guidiville Rancheria                                                                                                     |
| Shasta Gaughen | Director               | Pala Band of Mission Indians, Environmental Department ([PED](http://ped.palatribe.com/))                                |

: Tribal partners listed in ascending order by Affiliation

We also regularly receive critical feedback from the California Issues Workgroup of the US EPA Region 9 Regional Tribal Operations Committee ([RTOC](https://www.epa.gov/tribal-pacific-sw/regional-tribal-operations-committee-rtoc)). See the [Resource Chapter](https://cawaterboarddatacenter.github.io/tribal-water-data-map-manual/resources.html) of this User Manual for past presentations.

## Former OIMA Fellows & Interns

| Name              | Title             | Year      |
|-------------------|-------------------|-----------|
| Josh Davenport    | Stanford Fellow   | 2023      |
| Badhia Yunes Katz | CivicSpark Fellow | 2022-2023 |
