# Turning Data into Information is Challenging - Even More so with Racial Equity Data Work

Turning data into information in the context of racial equity involved navigating complex ethical considerations. The process requires an understanding of the potential impact on Black, Indigenous, and other People of Color (BIPOC) communities and the responsibility to mitigate perpetuating or reinforcing biases. Upholding ethical standards requires a commitment to maintaining privacy, accessibility, and fostering transparency throughout the data transformation process. Additionally, acknowledging the limitations of the data and being transparent about potential biases is essential for maintaining the integrity of the data and information generated and shared. The transformation of racial equity data into meaningful information requires a thoughtful and intentional approach which we will highlight in the next sections.

For example, many programs will rely on demographic and socioeconomic data, like those collected from the [U.S. Census](https://www.census.gov/programs-surveys/decennial-census/decade/2020/2020-census-main.html) and the [American Community Survey](https://www.census.gov/programs-surveys/acs) (ACS). Because the ACS is based on a sample, rather than all housing units and people, ACS estimates have a degree of uncertainty associated with them, called sampling error. In general, the larger the sample, the smaller the level of sampling error. To help users understand the impact of sampling error on data reliability, the Census Bureau provides a “margin of error” for each published ACS estimate. The margin of error, combined with the ACS estimate, gives users a range of values within which the actual “real-world” value is likely to fall.  It is important to acknowledge this uncertainty up front to be transparent with your audience about the data and conclusions you are drawing.  For more information on using [ACS data please see the Understanding and Using American Community Survey Data: What All Data Users Need to Know Handbook.](https://www.census.gov/programs-surveys/acs/library/handbooks/general.html)  Also for an interactive tool that measures the potential inaccuracies associated with relying on census data to enumerate demographic and socioeconomic characteristics in California please explore: <https://cacensus.maps.arcgis.com/apps/webappviewer/index.html?id=48be59de0ba94a3dacff1c9116df8b37>.\
\
Another example of how to tell your data story in a transparent way can be found on the Office of Environmental Health and Hazard Assessment CalEnviroScreen 4.0 Race and Equity Analysis.  <https://storymaps.arcgis.com/stories/f555670d30a942e4b46b18293e2795a7>
