# Inspiration

The impetus for developing this Data Equity Handbook began in August 2020 when the State Water Resources Control Board (State Water Board) publicly acknowledged that the historical effects of institutional racism must be confronted throughout government, and it directed staff to develop a priority plan of action. test megan's cool

Since then, the State Water Board, it's [Office of Information Management and Analysis](https://www.waterboards.ca.gov/resources/oima/) (OIMA) and OIMA's many internal and external partners have been developing and compiling material, and adding to this Data Equity Handbook as time and bandwidth allow.

This Data Equity Handbook is inspired by many sources, including:

-   [Water Boards Racial Equity](https://www.waterboards.ca.gov/racial_equity/) - [Resolution and Related Actions](https://www.waterboards.ca.gov/racial_equity/resolution-and-actions.html)
-   [Government Alliance on Race and Equity](https://www.racialequityalliance.org/home) (GARE)
-   [Openscapes](https://www.openscapes.org/) and their [Approach Guide](https://openscapes.github.io/approach-guide/)
-   [NOAA Fisheries (NMFS) Open Science Resource Book](https://nmfs-opensci.github.io/ResourceBook/)
