# Publish Water Boards Data

In accordance with the first principle of the [Water Board’s Open Data Resolution](https://www.waterboards.ca.gov/board_decisions/adopted_orders/resolutions/2018/rs2018_0032.pdf) (Resolution No. 2018-0032; see below), it is the responsibility of Water Boards data stewards to make our data open and accessible to the public.

> Make Data Accessible (“Open First”): our organization values transparency and strives to make all critical public data available in machine-readable datasets with metadata and data dictionaries.

When it comes to *doing* racial equity data work, a critical first step that should occur [***before** we consider taking on additional data related projects (e.g. making maps or other visualizations)*]{.underline} is to make the data that already exits and for which we steward and/or are responsible, open, transparent, and accessible to the public (as appropriate).

Not only does making data open help improve transparency, but doing so *before* you build your data interpretation tools (e.g. visualizations, reports) makes it easier for the communities we serve to access the data behind our interpretations and can ultimately help build relationships and trust.

Making data open is more than adding a spreadsheet or flat file to a webpage. Truly making your data open involves investing the time and resources required to follow the guidance on open data publishing at the Water Boards is available in the [Open Data Handbook](https://www.waterboards.ca.gov/resources/oima/cowi/open_data_handbook.html), including:

-   making data machine readable
-   formatting data in a way that aligns with common data standards
-   ensuring the quality of data is known and documented
-   going through data security process
-   generating and ensuring all metadata and documentation related to the data is comprehensive and complete
-   publishing data and all documentation in an open data platform / format

Contact OIMA ([OIMA-Helpdesk\@waterboards.ca.gov](mailto:OIMA-Helpdesk@waterboards.ca.gov)) for specific guidance or support with navigating through the open data publication process at the Water Boards.
