# Resources

Here you will find a curated list of presentations, webpages and other resources related to the development, implementation and scaling of the principles and practices outlined in this Data Equity Handbook.

All Water Boards authors are **bolded** below.

## Other Equity & Data Handbooks / Toolkits / Guides

-   [**Water Boards Developed Racial Equity Data Tools**](https://gispublic.waterboards.ca.gov/portal/apps/experiencebuilder/template/?data_id=dataSource_14-0%3A10&id=b02e68db0fa7452aad0b08d3c65d4a93)

-   [**Water Boards Environmental Justice Roundtable Resource Catalog**](https://cawaterboards.sharepoint.com/:w:/r/sites/WB-OPP-EJRoundtable/Materials/Resources/EJRT_Resources%20Catalogue.docx?d=wbf0bd2eff6e943f0ad5c9972554eb1f4&csf=1&web=1&e=b39KxT)

-   [GARE Racial Equity Toolkit: An Opportunity to Operationalize Equity](https://www.racialequityalliance.org/viewdocument/racial-equity-toolkit-an-opportuni-2)

-   [Beyond Compliance Network Advocacy Toolkit](https://beyondcompliance.pubpub.org/pub/c90gqevm/release/2)

-   [Academic Data Science Alliance Data Science Ethos](https://ethos.academicdatascience.org/)

-   [CA Water Boards College of Water Informatics Data Toolkit](https://www.waterboards.ca.gov/resources/oima/cowi/data_training.html)

-   [500 Women Scientists Guide for Inclusive Scientific Meetings](https://500womenscientists.org/inclusive-scientific-meetings)

-   City of Oakland \| [OakDOT Geographic Equity Toolbox (oaklandca.gov)](https://www.oaklandca.gov/resources/oakdot-geographic-equity-toolbox)

-   City of Portland Racial Equity Toolkit: <https://www.portlandoregon.gov/oehr/71685>

-   Pierce County (Washington State) utilizes an [Equity Index mapping tool](http://www.piercecountywa.gov/equityindex) to help inform diversity, equity, and inclusion considerations throughout County decision-making.

-   The City of Seattle utilizes a [Racial and Social Equity Index](https://maps.seattle.gov/RSEIndex) that many departments use for prioritization and evaluation/analysis. A [user guide](#0) is also available.

-   New York City government's online interactive equity data tool [EquityNYC](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequity.nyc.gov%2F&data=05%7C01%7Cnicholas.martorano%40waterboards.ca.gov%7C87a614b2e3db4c85368c08dbc55a8595%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638320764855634179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r%2Br4%2BybTh130ovhG12PjYHQYqVHlz4jSB8gXj3KTnAI%3D&reserved=0), including a [Mapping Equity tool](https://equity.nyc.gov/mapping-equity).

-   **The Water Boards Office of Research Planning and Performance Water Conservation and Urban Water folks tool: <https://www.waterboards.ca.gov/water_issues/programs/conservation_portal/water-use-explorer/>**

-   **The Water Boards Office of Research Planning and Performance Vulnerable Communities Platform: <https://vcp-beta-1-1-gov-opr.hub.arcgis.com/>**

-   Racial Equity Workforce Planning (CalEPA) - [Practices to Advance Racial Equity in Workforce Plannin (ca.gov)](https://calepa.ca.gov/wp-content/uploads/sites/6/2021/11/Practices-to-Advance-Racial-Equity-in-Workforce-Planning.sw_.jh_.pdf?emrc=175a3b)

-   Caltrans Beta Equity Index Map: <https://caltrans.maps.arcgis.com/apps/webappviewer/index.html?id=8ff3d27cdc1a4e8da0ae09c6b076a253>

-   **Water Boards Division of Drinking Water SAFER Outreach Tool: <https://gispublic.waterboards.ca.gov/portal/apps/webappviewer/index.html?id=70d27423735e45d6b037b7fbaea9a6a6>**

## GIS Resources

-   <https://learn.arcgis.com/en/projects/create-a-social-equity-index-to-improve-public-health/>

-   [Extend_the_Reach_of_Your_GIS (1).pdf](https://github.com/user-attachments/files/16605635/Extend_the_Reach_of_Your_GIS.1.pdf)

-   Additional [best practices from Esri](https://doc.arcgis.com/en/hub/content/prepare-your-content.htm#:~:text=Tags%E2%80%94These%20help%20users%20discover,facilitate%20their%20discovery%20and%20use.) on improving the quality of content within a Hub site.

-   Also worth noting that ArcGIS Online comes some general [categories](https://doc.arcgis.com/en/arcgis-online/reference/content-categories.htm) that are derived from ISO and INSPIRE. Those could be good starting points, but my hunch is that you’re going to want to add additional categories to better support filtering and finding the right datasets.

## Data Ethics and Data Sovereignty Resources

-   GovOps medium article on Data Ethics (<https://medium.com/caldata/practical-data-ethics-summary-of-what-were-learning-24d0e9d89cd0>)

-   Federal data ethics framework (<https://resources.data.gov/assets/documents/fds-data-ethics-framework.pdf>)

-   [Operationalizing the CARE and FAIR Principles for Indigenous data futures](https://www.nature.com/articles/s41597-021-00892-0)

-   The Data Ethics Canvas is designed to help identify potential ethical issues associated with a data project or activity. It promotes understanding and debate around the foundation, intention and potential impact of any piece of work, and helps identify the steps needed to act ethically: <https://directory.civictech.guide/listing/the-odis-data-ethics-canvas>

-   Ethics Framework (CalData): <https://medium.com/caldata/practical-data-ethics-summary-of-what-were-learning-24d0e9d89cd0> ; Framework at a Glance: <https://drive.google.com/file/d/14Hl6i2w3CImqrzLLYuB27PFD6DNdzdHX/view>

-   FAIR data principles for community centered data formats: <https://www.nature.com/articles/s41597-022-01606-w> Research practices documents related to using data for equity - working with communities to find data to use in equity work, and how to best collect and use demographic (ethnic and racial equity, sexual orientation, and gender identity data, specifically).

-   Article - Mapping for Whom? Communities of Color and the Citizen Science Gap: <https://acme-journal.org/index.php/acme/article/view/2178/1654>

-   Global Indigenous Digital Alliance guidance on using CARE principles for Indigenous data governance: <https://www.gida-global.org/care>

-   At the most basic level, taking an equity lens in Data Wise involves having a team ask itself probing questions at each step of the improvement process. This document provides a look at how to use a data wise techniques with a racial equity lens. <https://www.ascd.org/el/articles/looking-at-data-through-an-equity-lens>

-   "collecting/using demographic data" - <https://www.urban.org/sites/default/files/publication/103830/five-ethical-risks-to-consider-before-filling-missing-race-and-ethnicity-data-workshop-findings_0.pdf>

## Presentations

[Analyzing Water Boards and Demographic Data for Equity](https://cawaterboards.sharepoint.com/:b:/r/sites/WB-OPP-EJRoundtable/Materials/Racial%20Equity%20Data%20Subcommittee/Webinars/Demo%20Webinar%20with%20DataMade%20Coaches_25June24/Hannah%27s%20slides%20on%20racial%20equity%20data%20analysis.pdf?csf=1&web=1&e=eNCc0K). Jun 2024. Hannah Cushman Garland. State Water Board Racial Equity Data Subcommittee Webinar. [Recording](https://cawaterboards.sharepoint.com/:v:/r/sites/WB-OPP-EJRoundtable/Materials/Racial%20Equity%20Data%20Subcommittee/Webinars/Demo%20Webinar%20with%20DataMade%20Coaches_25June24/DataMade%20Webinar%20Recording_25June24.mp4?csf=1&web=1&e=oOuGyf) \| [Download and Use the Code](https://drive.google.com/file/d/1yva-EE0JyQna4c5RN73TJ7F0YUIRTXCI/view?usp=sharing) \| [View Code](https://datamade.github.io/waterboard-coaching/)

## Relevant Government Documents

### [State of California Agency Resources]{.underline}

#### [Governor's Office]{.underline}

-   Governor Executive Order on Racial Equity: <https://www.gov.ca.gov/wp-content/uploads/2022/09/9.13.22-EO-N-16-22-Equity.pdf?emrc=c11513>

-   Equity in the State Revolving Fund use for infrastructure: <https://www.policyinnovation.org/publications/a-fairer-funding-stream>

#### [California Water Boards]{.underline}

-   Racial Equity Resolution (2021) - [English](https://www.waterboards.ca.gov/board_decisions/adopted_orders/resolutions/2021/rs2021_0050.pdf), [Español](https://www.waterboards.ca.gov/board_decisions/adopted_orders/resolutions/2021/rs2021_0050_sp.pdf)
-   Racial Equity Action Plan (2023) - [English](https://www.waterboards.ca.gov/racial_equity/docs/racial-equity-action-plan-final-en.pdf), [Español](https://www.waterboards.ca.gov/racial_equity/docs/racial-equity-action-plan-final-sp.pdf)
-   [Racial Equity Resolution Annotated References](https://www.waterboards.ca.gov/racial_equity/docs/Racial-Equity-Resolution-Annotated-References-2021.11.pdf) (2021)

#### [California Office of Data and Innovation]{.underline}

-   [California Data Strategy Report](https://innovation.ca.gov/reports/data-strategy-report-2024/) (2024)
-   [California Data Strategy](https://innovation.ca.gov/pdf/CalData_Californias_Data_Strategy_2020.pdf) (2020)

#### [California Department of Transportation (Caltrans)]{.underline}

-   Considering Equity in Community Impact Analysis for Projects <https://dot.ca.gov/-/media/dot-media/programs/environmental-analysis/documents/ser/equity-guidance-a11y.pdf>

#### [Office of Environmental Health and Hazard Assessment (OEHHA)]{.underline}

-   CalEnviroScreen 4.0 and how race and ethnicity is analyzed within that tool and the CES score correlations: <https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40raceanalysisf2021.pdf>

### [Local City and County Resources]{.underline}

-   City of Oakland \| [OakDOT Geographic Equity Toolbox (oaklandca.gov)](https://www.oaklandca.gov/resources/oakdot-geographic-equity-toolbox)

-   City of Portland Racial Equity Toolkit: <https://www.portlandoregon.gov/oehr/71685>

-   Pierce County (Washington State) utilizes an [Equity Index mapping tool](http://www.piercecountywa.gov/equityindex) to help inform diversity, equity, and inclusion considerations throughout County decision-making.

-   The City of Seattle utilizes a [Racial and Social Equity Index](https://maps.seattle.gov/RSEIndex) that many departments use for prioritization and evaluation/analysis. A [user guide](#0) is also available.

-   New York City government's online interactive equity data tool [EquityNYC](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequity.nyc.gov%2F&data=05%7C01%7Cnicholas.martorano%40waterboards.ca.gov%7C87a614b2e3db4c85368c08dbc55a8595%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638320764855634179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r%2Br4%2BybTh130ovhG12PjYHQYqVHlz4jSB8gXj3KTnAI%3D&reserved=0), including a [Mapping Equity tool](https://equity.nyc.gov/mapping-equity).

### [Other State Level Resources]{.underline}

-   MN DOT Governance and Best Practices: A tailored document like this would be useful to encourage contributors to follow the same guidelines and understand which groups or tags need to be added for the data to be ingested properly. - [MnDOT Governance and Best Practices and User Requirements (1).docx](https://github.com/user-attachments/files/16605638/MnDOT.Governance.and.Best.Practices.and.User.Requirements.1.docx)

### [National Level Resources]{.underline}

-   [The Environmental Justice Science, Data, and Research Plan](https://www.whitehouse.gov/wp-content/uploads/2024/07/NSTC-EJ-Research-Plan-July-2024.pdf) (2024)
-   [Year of Open Science Fact Sheet](https://www.whitehouse.gov/ostp/news-updates/2023/01/11/fact-sheet-biden-harris-administration-announces-new-actions-to-advance-open-and-equitable-research/) (2023)
-   <https://www.census.gov/programs-surveys/acs/data.html> - The American Community Survey (ACS) releases new data every year through a variety of data tables that you can access with different data tools.
-   <https://www.census.gov/programs-surveys/acs/library/handbook> - You can use American Community Survey (ACS) data in different ways and for different reasons. Each one of our downloadable PDF handbooks helps a particular group with specific how-to instructions and/or case studies.
-   US EPA guidance for Assessing Environmental Justice in Regulatory Analysis <https://www.epa.gov/system/files/documents/2023-11/ejtg_revision_110823_508compliant_0.pdf>
-   Guide from the U.S. Department of Health and Human Services on how to conduct an equity assessment of a policy or program: [In-Depth Equity Assessment Guide \| ASPE (hhs.gov)](https://aspe.hhs.gov/reports/equity-assessment-guide)
-   [FACT SHEET: Biden-⁠Harris Administration Releases Annual Agency Equity Action Plans to Further Advance Racial Equity and Support for Underserved Communities Through the Federal Government](https://www.whitehouse.gov/briefing-room/statements-releases/2024/02/14/fact-sheet-biden-harris-administration-releases-annual-agency-equity-action-plans-to-further-advance-racial-equity-and-support-for-underserved-communities-through-the-federal-government/)
-   <https://www.usich.gov/resources/uploads/asset_library/Racial_Equity_Data_Guidebook.pdf> (link broken?) - The U.S. Interagency Council on Homelessness (USICH) is the only federal agency with a sole mission focused on preventing and ending homelessness in America. The council consists of 19 federal agencies that help create and catalyze implementation of the Federal Strategic Plan to Prevent and End Homelessness.
-   <https://www.whitehouse.gov/wp-content/uploads/2022/04/eo13985-vision-for-equitable-data.pdf> - From the White House Equitable Data Working Group
-   <https://cssp.org/wp-content/uploads/2021/09/Our-Identities-Ourselves-Project-Infographic-FINAL.pdf> - Center for the Study of Social Policy. This is the first phase of a larger project whose goal is to share best practices for collecting data about race, ethnicity, and other demographic information including sexual orientation, gender identity and expression (SOGIE); national origin; language spoken; disability; religion; and tribal affiliation in child welfare agencies nationwide.
-   [CDC guidance: Principles for Using Public Health Data to Drive Equity A guide to embedding equitable practices throughout the data life cycle](https://www.cdcfoundation.org/data-equity-principles?inline)
-   [Federal Register :: Initial Proposals For Updating OMB's Race and Ethnicity Statistical Standards](https://www.federalregister.gov/documents/2023/01/27/2023-01635/initial-proposals-for-updating-ombs-race-and-ethnicity-statistical-standards)
-   Actionable Intelligence for Social Policy (AISP) Centering for Equity Toolkit: <https://aisp.upenn.edu/resource-article/a-toolkit-for-centering-racial-equity-throughout-data-integration/>
-   Urban Institute's Principles for Advancing Equitable Data Practice: <https://www.urban.org/sites/default/files/publication/102346/principles-for-advancing-equitable-data-practice.pdf>
-   General Data Management resource hub from the National Institute of Health that includes FAIR principles, metadata practices etc. <https://sharing.nih.gov/data-management-and-sharing-policy/data-management>
-   Hero Database with Racial Equity Resources collated from the National : <https://hero.epa.gov/hero/index.cfm/project/page/project_id/3611>
-   <https://nationalequityatlas.org/> The National Equity Atlas is America's most detailed report card on racial and economic equity.
-   US EPA has [guidance](https://www.epa.gov/geospatial/guidance-content-item-metadata-arcgis-online) for content metadata in ArcGIS Online.
-   [Initial Proposals for Revising the Federal Race and Ethnicity Standards \| OMB \| The White House](https://www.whitehouse.gov/omb/briefing-room/2023/01/26/initial-proposals-for-revising-the-federal-race-and-ethnicity-standards/)

## Relevant Literature

O’Brien, M., Duerr, R., Taitingfong, R., Martinez, A., Vera, L., Jennings, L.L., Downs, R.R., Antognoli, E., ten Brink, T., Halmai, N.B., David-Chavez, D., Carroll, S.R., Hudson, M. and Buttigieg, P.L. (2024) ‘[Earth Science Data Repositories: Implementing the CARE Principles](https://doi.org/10.5334/dsj-2024-037.)’, *Data Science Journal*, 23(1), p. 37.

## Websites

-   [Racial Equity at the Water Boards](https://www.waterboards.ca.gov/racial_equity/)
-   [Openscapes at the Water Boards](https://cawaterboarddatacenter.github.io/swrcb-openscapes/)
-   [California Office of Data and Innovation](https://innovation.ca.gov/)
-   [Government Alliance on Race and Equity](https://www.racialequityalliance.org/home) (GARE)
-   [California Indian Water Rights Study](https://water.calindian.org/)
