# Surveys

A good comprehensive guide for survey design can be found here:  <https://files.eric.ed.gov/fulltext/ED619797.pdf> 

Creating surveys that yield actionable insights is about details. And writing effective survey questions is the first step. You do not have to be an expert to build and distribute an effective online survey, but by checking your survey against tried-and-tested benchmarks, you can help ensure you are collecting the best data possible.  

Tips for Building an Effective Survey:

1.  Make Sure That Every Question Is Necessary.

2.  Keep it Short and Simple.

3.  Ask Direct Questions.

4.  Ask One Question at a Time.

5.  Avoid Leading and Biased Questions.

6.  Speak Your Respondent's Language.

7.  Use Response Scales Whenever Possible.

8.  Avoid Using Grids or Matrices for Responses.

9.  Rephrase Yes/No Questions if Possible

10. Take Your Survey for a Test Drive

<https://www.qualtrics.com/blog/10-tips-for-building-effective-surveys/>

## **Picking a Survey Software**

Most Water Board staff will use Microsoft Forms which is available to all staff through the Microsoft 365 suite of applications.  Microsoft Forms has a lot of advantages because of its integration with other Microsoft tools like Excel and PowerBi which allow for the survey results to be analyzed and visualized.  Here is video on how to make that connection between Forms and PowerBi via Sharepoint that allows for consistent updating of results:  <https://youtu.be/XBFVDedwLiY?si=O161oYja-FBhG1W7> 

One issue with Microsoft Forms and other free software like Google Forms is that they produce wide data in Excel of Google Sheets.  This type of data is more difficult to transform.
