# Data Collection

::: callout-important
You should have addressed this during the [Plan](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html) & [Prepare](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/prep.html) phase of your process...but just in case you haven't (yet) or you need a refresher - we're restating here:

**Achieving racial equity outcomes means that race can no longer be used to predict life outcomes and outcomes for all groups are improved** ([Glossary](https://cawaterboarddatacenter.github.io/equity-data-handbook/get-started/common-language.html#glossary))

So, as you begin to collect the data for your project, be sure it includes:

1.  Data that can represent your management question(s) or project objectives.

2.  Data that can tell us something about the extent to which we are achieving equity outcomes. This may be limited to simple demographics data - but it could also be something more! Working with Tribal and community experts to decide what type(s) of data are most applicable to and reflective of their lived experiences as they relate to your management questions and project objectives is a great place to start!
:::

The data related to your project may come from direct human observation, laboratory and field instruments, experiments, simulations, surveys, and/or compilations of data from other sources. Below we focus on data that can be downloaded from open data sources, and survey guidance.

## Data Limitations

As you begin to collect the data required for your project, it's important to remember that ALL data have limits in what they can actually tell us, constraints on how they should be used appropriately, and biases related to initial data collection or generation - and it's crucial to be aware of and account for them during your project.

In addition to data limitations related to data quality or analysis methods (e.g., insufficient quality, low sample size, data gaps; see the the [Quality Assurance](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/qaqc.html) and [Data Analysis](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/analysis.html) pages for more details), be sure to also keep the below considerations in mind so that you can prepare and analyze your data in a way that supports the advancement of equity, inclusion, and justice.

::: callout-note
### Remember - it's OK to have data gaps! 

It's OK to have some data gaps, and in the case of conducting data analyses with a racial equity lens, gaps will be the norm. What's important is to acknowledge what gaps exist, document how you will account for them, and (ideally) set a course for filling those gaps, as appropriate.
:::

### Unconscious bias of data sources

We all have unconscious biases and operate in inequitable and unjust systems. That can unconsciously and unintentionally impact how data are collected and result in datasets that reflect those biases. Take time to ask the following questions about the data you're interested in using for your project so you can have a better understanding of the data's context and be better able to detect and account for potential biases of said data:

-   Who collected the data?
-   Why were these specific data collected? What were the data collection goals?
-   How was data collected?
-   What was prioritized during data collection?
-   What assumptions were made during data collection?

### Who is missing from the data

It's not uncommon for project teams to have gaps in data, even after all of your diligent work and investment into the [planning](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html) and [data preparation](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/prep.html) steps of the project. This limitation of the data may be out of your control - especially when you are using data from external sources. Quality data regarding marginalized communities is often lacking. For example, recent research has shown that [US lakes are monitored disproportionately less in communities of color](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/fee.2803) - similar trends may be likely in other data sources.

When this happens, it's important to acknowledge, document, and accessibly communicate those gaps and who is not adequately represented in your data product. In some cases, It may be appropriate to still present or analyze these data and also present caveats for the data limitations. In other cases, it may be more appropriate to rely only on qualitative discussion based on information derived from background research and feedback from affected communities.

## Consider how you will group the data

As you collect your data, start thinking through how the raw data you are collecting is already grouped and how you intend on grouping the data. You may not be able to decide on how you will ultimately aggregate or disaggregate the data until you are further along in the [analysis](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/analysis.html) or [visualization](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/vis.html) stages - but it's important to begin thinking about this issue during the data collection phase for the reasons outlined below.

How we aggregate or disaggregate the data can impact which groups are "seen" and represented (or not) in our data products. This can also influence who is centered, valued, or prioritized in the narrative of the visualization, and who is excluded.

Carefully consider how groups are lumped or split - by aggregating many groups in the visualization beyond what might be statistically necessary (and not acknowledging who is being grouped together and why), we can unintentionally misrepresent said groups, minimize inequities and perpetuate invisible and erased experiences of those communities. On the other hand, when analysts create a subgroup, they may be shifting the focus of analysis to a specific population that is likely already over-surveilled ([Centering Racial Equity Throughout Data Integration](https://aisp.upenn.edu/wp-content/uploads/2022/07/AISP-Toolkit_5.27.20.pdf)).

The [UNC Health’s Equity and Inclusion Analytics Workgroup](https://ncstoragemlunchealthcare.blob.core.windows.net/public/pdf-system-data-visualization-standards.pdf) recommends we ask ourselves the following questions when we're thinking about how we will aggregate the data (or not):

-   **Is important data/nuance lost by combining categories?** Ensure there is not a meaningful difference in our ability to understand equity outcomes between groups that would be lost if combined.

-   **Does the inclusion of uncombined data negatively impact the interpretation of the data visualization?** Having too many groups can make visualizations cluttered and hard to interpret. Additionally, disaggregation leads to smaller group sizes, which can make comparisons to larger groups more difficult and quantifying statistical significance more challenging. For those reasons, it can sometimes be best to combine groups.

-   **Does sharing uncombined data compromise confidential information (e.g., Personal Identifiable Information) or information considered private by the community from which it comes (e.g., locations of sacred practices)?** This will depend on the audience you are sharing the visualization with (e.g. internal vs public) and what information it contains.

If you ultimately decide to aggregate / combine groups, be sure to:

1.  **Avoid creating a dichotomy of races.** Don’t use “White” vs. “non-White” or “people of color.” Rather, disaggregate the “non-White” group to show the diversity among communities.

2.  **Be transparent** about why you're making those decisions (including the trade offs you considered) and documenting those decisions accordingly.

3.  **Acknowledge who is now not included** in the data or visualization and explain what groups have been combined and why. Use comments, tooltips, or footnotes that can be easily accessed within the visualization to make it easier for users to find this information.

4.  **Think carefully about how groups are lumped in the "other" category** of our analysis or visualization. Sometimes it's necessary to combine groups into a single "other" category (e.g. to generalize small groups to protect confidentiality or to achieve adequate sample size for your analysis). The Urban Institute's [Do No Harm Data Visualization Recommendations](https://www.urban.org/sites/default/files/2021/06/08/do-no-harm-guide-recommendations.pdf) include considering alternatives to using the term "other" as a catch-all category, including:

    -   Another \_\_\_\_\_\_ (e.g. Another race or Another group)
    -   Additional \_\_\_\_\_\_ (e.g. Additional races or Additional languages)
    -   All other self-descriptions
    -   People identifying as other or multiple races
    -   Identity not listed
    -   Identity not listed in the survey or dataset

## Common Data Sources

In most cases, the Water Boards programs were not developed or designed to collect the types of data needed to conduct analyses with an equity lens as a matter of process which means that most will rely on external data sources. Below we have provided a list of common data sources that can tell us something about the extent to which we are achieving equity outcomes.

### Demographics Data

Adding demographics data to your data project can help increase understanding of potential correlations or relationships between your data and demographic and socioeconomic characteristics of locations of interest. More specifically, the integration of demographics data into your data project can highlight the extent to which race can still be used to predict outcomes associated with your project and therefore underscore where and to what extent racial equity outcomes have not yet been achieved.

#### **Demographics Data Needs Context**

It’s important to remember to provide context about your project before trying to communicate demographics related results or answers to specific racial equity questions posed by our Board, the public, or our partners in this work. Contextual topics could include:

-   What is your program/project about? What is the mission?
-   What is your program/project meant to do? What are your objectives/goals?
-   How well does your program/project do these things now (aka Performance Report)?
-   What approaches are you taking with this project to advance equity outcomes?

Communicating this contextual information may require different complementary modes of communication (e.g. presentation, fact sheets, visualizations), but investing the time to provide that grounding and framing will help the audience understand how you are approaching your data work with an equity lens within the scope of your program/project. 

#### **Demographics Data Sources**

The data sources many use to make inferences related to demographic and socioeconomic characteristics are from the [United States Census Bureau](https://www.census.gov/data.html) and the associated [American Community Survey (ACS) Data](https://www.census.gov/programs-surveys/acs/data.html).

While we are fortunate to have just updated this dataset in 2020 there are limitations and potential inaccuracies associated with relying solely on census data to enumerate demographic characteristics within a given census tract. This [tool from the Department of Finance exists to measure this limitation](https://cacensus.maps.arcgis.com/apps/webappviewer/index.html?id=48be59de0ba94a3dacff1c9116df8b37).

The ACS also has a [Handbooks for Data Users](https://www.census.gov/programs-surveys/acs/library/handbook) to make it easier for folks to use the data appropriately.

#### **Demographics Data Integration Methods**

Depending on what demographics data sources you decide to use, the methods needed to combine, overlay, or compare with the data you are interested in may vary. Below we outline methods of comparing demographics data to point, line, and polygon data types.

*\<insert content from Use Case Page here!\>*

[Estimating Demographics of Custom Spatial Features](https://daltare.github.io/example-census-race-ethnicity-calculation/example_census_race_ethnicity_calculation.html) is another detailed example of how to use the R programming language to estimate demographics and other characteristics with U.S. census data to be used for custom spatial features, and can be tailored to programs with the help of a data scientist proficient in R and staff familiar with the program.

### CalEnviroScreen

[CalEnviroScreen](https://oehha.ca.gov/calenviroscreen) is a mapping tool that helps identify California communities that are most affected by many sources of pollution, and where people are often especially vulnerable to pollution’s effects. CalEnviroScreen can be a helpful tool in creating visualizations and performing analysis as it provides a number of indices, as well as a "rolled-up" score that combines environmental and demographic data together. As with any dataset or visualization tool there can be things to consider, a couple of which are discussed below.

#### **Missing Values for CalEnviroScreen Scores**

Users conducting an analysis with the [CalEnviroScreen (CES) 4.0 dataset](https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40) should be aware that it contains missing values, both for individual indicators and overall CES scores. These missing values are distinct from zeros, which are also in the CES dataset.

In the CES 4.0 data (for the version available as of April 2023), the [shapefile containing CES 4.0 scores](https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40shpf2021shp.zip) encodes these missing values as negative numbers (-999 for most variables, and -1998 for one variable). The [Excel workbook containing CES 4.0 scores](https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40resultsdatadictionaryf2021.zip) encodes these missing values as NA.

Also, note that the CalEnviroScreen 3 shapefile (June 2018 update version) encoded missing values as 0, so users should be aware of this change if/when updating an analysis from CES 3 to CES 4.0 data.

Users should account for these missing values – and their different encodings – as needed when doing any analysis using CES data.

For more information about the missing (and zero) values in the CES 4.0 dataset, see the data dictionary (PDF file) that accompanies the CalEnviroScreen 4.0 results Excel workbook, both of which are available for [download as a zip file](https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40resultsdatadictionaryf2021.zip).

#### **Inconsistent Census Tract Boundaries in CalEnviroScreen 4.0 Shapefile**

In the CES 4.0 data (for the version available as of April 2023), the [shapefile containing CES 4.0 scores](https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40shpf2021shp.zip) uses a simplified version of the polygons that represent 2010 census tracts. The boundaries of the census tracts defined by these simplified polygons do not always align with the boundaries of neighboring census tracts, resulting in slight gaps or overlaps between some neighboring census tracts. These inconsistencies are not likely to have a significant impact on most uses of the CES data, but they could impact some types of analysis based on CES data. For example, when assessing sites or facilities based on the CES score of the census tract they are located in, sites located near a census tract boundary could be associated with more than one census tract (and more than one CES score) in areas where there are overlapping census tract polygons, or not associated with any census tract (and no CES score) in areas where there are gaps between census tract polygons.

This issue may be addressed in a future release of the CES dataset; in the meantime, a possible workaround is to use the official 2010 census tract boundaries from the US Census Bureau for any calculations, then use census tract IDs to tie this information to the associated CES score for each tract.

### U.S. EPA EJScreen

[EJScreen](https://www.epa.gov/ejscreen) is EPA's environmental justice mapping and screening tool that provides EPA with a nationally consistent dataset and approach for combining environmental and socioeconomic indicators.

First-time users may find the 5-minute [EJScreen in 5: A Quick Overview of EJScreen](#0 "This link opens a new webpage.") video helpful as an introduction to the tool.

## Surveys

There may be instances where the data you need are not already available and you need to collect it yourself through the use of survey(s).

### Survey Design

Creating surveys that yield actionable insights is all about the details - and writing effective survey questions is the first step. You do not have to be an expert to build and distribute an effective online survey, but by checking your survey against tried-and-tested benchmarks, you can help ensure you are collecting the best data possible.  

Tips for Building an Effective Survey:

1.  Make Sure That Every Question Is Necessary
2.  Keep it Short and Simple
3.  Ask Direct Questions
4.  Ask One Question at a Time
5.  Avoid Leading and Biased Questions
6.  Speak Your Respondent's Language
7.  Use Response Scales Whenever Possible
8.  Avoid Using Grids or Matrices for Responses
9.  Rephrase Yes/No Questions if Possible
10. Take Your Survey for a Test Drive

Guides for good survey design include:

-   [Creating Effective Surveys - Best Practices](https://files.eric.ed.gov/fulltext/ED619797.pdf)
-   [How to Create an Effective Survey](https://www.qualtrics.com/blog/10-tips-for-building-effective-surveys/)

### **Beware of Common Types of** Survey Bias

*Add content*

### **Picking a Survey Software**

Most Water Board staff will use Microsoft Forms which is available to all staff through the Microsoft 365 suite of applications. Microsoft Forms has a lot of advantages because of its integration with other Microsoft tools like Excel and PowerBI which allow for the survey results to be analyzed and visualized.  See this [6 min video on Using Microsoft Forms data with Power BI](https://youtu.be/XBFVDedwLiY?si=O161oYja-FBhG1W7) for guidance on how to make the connection between Forms and PowerBi via Sharepoint that allows for consistent updating of results

Note that those who use Microsoft Forms and other free software like Google Forms will likely need to transform the form output from a wide format to a long format for analysis. See the [Processing Data with an Equity Lens](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/process.html#processing-data-with-an-equity-lens) section of the Data Processing page for more guidance.

## Internal and Confidential Data

In addition to the data sources listed above, most organizations including the Water Board have various types of Administrative Data which includes internal demographics data related to the workforce in the organization. This data is normally confidential but can be very valuable when working on addressing workforce equity. If and when these data are used, it is critical to ensure the protection and security of the data to preserve confidentiality through the development and sharing (or not) of the final data product. See the [Data Collection and Processing section of the Planning Phase](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/prep.html#data-collection-processing) for more guidance.

## Additional Resources

-   Demographics Analyses
    -   [Analyzing Water Boards and Demographic Data for Equity](https://cawaterboards.sharepoint.com/:b:/r/sites/WB-OPP-EJRoundtable/Materials/Racial%20Equity%20Data%20Subcommittee/Webinars/Demo%20Webinar%20with%20DataMade%20Coaches_25June24/Hannah%27s%20slides%20on%20racial%20equity%20data%20analysis.pdf?csf=1&web=1&e=eNCc0K). Jun 2024. Hannah Cushman Garland. State Water Board Racial Equity Data Subcommittee Webinar. [Recording](https://cawaterboards.sharepoint.com/:v:/r/sites/WB-OPP-EJRoundtable/Materials/Racial%20Equity%20Data%20Subcommittee/Webinars/Demo%20Webinar%20with%20DataMade%20Coaches_25June24/DataMade%20Webinar%20Recording_25June24.mp4?csf=1&web=1&e=oOuGyf) \| [Download and Use the Code](https://drive.google.com/file/d/1yva-EE0JyQna4c5RN73TJ7F0YUIRTXCI/view?usp=sharing) \| [View Code](https://datamade.github.io/waterboard-coaching/)
-   CalEnviroScreen
    -   Analysis of Race/Ethnicity and CalEnviroScreen 4.0 Scores [Storymap](https://storymaps.arcgis.com/stories/f555670d30a942e4b46b18293e2795a7) \| [Report](https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40raceanalysisf2021.pdf)
    -    [SB 535 Disadvantaged Communities](https://oehha.ca.gov/calenviroscreen/sb535)
    -   [CalEnviroScreen page of the California Water Boards Racial Equity Resource Hub](https://gispublic.waterboards.ca.gov/portal/apps/experiencebuilder/experience/?draft=true&id=b02e68db0fa7452aad0b08d3c65d4a93&page=page_6&views=View-4)
-   U.S. EPA EJScreen
    -   [EJScreen User Guide](https://ejscreen.epa.gov/mapper/help/ejscreen_help.pdf "This link opens a new webpage.") for navigating the various features of the tool,
    -   [EJScreen Glossary](https://www.epa.gov/ejscreen/ejscreen-map-descriptions "This link opens a new webpage.") for better understanding the map layers and indicators being displayed in the tool, and
    -   [Frequent Questions about EJScreen](https://www.epa.gov/ejscreen/frequent-questions-about-ejscreen "This link opens a new webpage.")

### *Move to Use Case Page*

Example - [SAFER Fund Expenditure Plan](https://www.waterboards.ca.gov/water_issues/programs/grants_loans/sustainable_water_solutions/safer.html)

Section VIII.G. Racial Equity and Environmental Justice provides several tables with data that incorporates demographics data. The tables and the text lack clarity and in depth analysis on why the data is telling the story it is. Race and ethnicity of the populations served by the systems likely isn't the only only difference between the systems. Are there other factors that are associated with different populations that could be driving the imbalance in failing systems and funding? Perhaps, the majority-Hispanic population systems are much larger, or older, or have more severe problems. An apples to apples comparison would look at the major factors that determine cost and compare the racial difference between those subgroups. For example, comparing the racial and ethnic differences between systems of medium sized cities with a water treatment plant built within the past 30 years. Making these proportions more explicit and adding a section where Hispanics population systems get more funding, proportionally and list some additional explanatory factors that should be explored.
