# SWAMP

## Background

California's Surface Water Ambient Monitoring Program (SWAMP) was established by the California Legislature in 2000 ([Assembly Bill 982](http://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=199920000AB982); Ducheny 1999) to develop a comprehensive statewide surface water quality monitoring program to assess the condition of California’s surface waters and watersheds.

There are four statewide monitoring programs, including:

-   [The Bioaccumulation Monitoring Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring.html)
-   [The Bioassessment Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioassessment/)
-   [The Freshwater and Estuarine Harmful Algal Bloom (FHAB) Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/freshwater_cyanobacteria.html)
-   [The Toxicology and Contaminants Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/spot/)

SWAMP is also leading the [SWAMP environmental DNA Metabarcoding Monitoring and Analysis Project (SeMMAP)](https://experience.arcgis.com/experience/db3a30220d0d4bdea684781cdaef5230/).

The California State Water Resources Control Board adopted principles of open data ([Assembly Bill 1755 (Bloom, 2016)](https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=201520160AB1755); [State Board Resolution 2018-0032](https://www.waterboards.ca.gov/board_decisions/adopted_orders/resolutions/2018/rs2018_0032.pdf)) and racial equity ([State Water Board Resolution 2021-0050](https://www.waterboards.ca.gov/board_decisions/adopted_orders/resolutions/2021/rs2021_0050.pdf)) and directed programs to strategically implement those principles into their activities. In preparation for and in response to these Resolutions, SWAMP has dedicated resources to make its monitoring data open, accessible, and used. Moving beyond basic open data requirements, SWAMP has embraced open science and racial equity as core, interconnected values and has begun to operationalize and implement them into their work.

Below are use cases of how SWAMP statewide programs and projects are working to operationalize open science and equity principles and practices into all phases of the data life cycle. Each program and project have differing levels of resources, capacity, and partnerships which have resulted in differing approaches. SWAMP does not claim to have finished operationalizing open science and equity principles and practices into all phases of the data life cycle. Rather, SWAMP sees each of the use cases below as iterative, living, and continuously improving works in progress.

## Bioaccumulation Monitoring Program

The Bioaccumulation Monitoring Program funds and coordinates the collection and analysis of tissue from fish (and sometimes shellfish) to understand which fish are safer to eat in water bodies throughout the state.

### Realignment

::: callout-note
The [Program Realignment](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring/program_realignment.html) process focuses on improving the [Plan and Prepare](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/), [Collect and Process](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/), and [Publish and Share](https://cawaterboarddatacenter.github.io/equity-data-handbook/share.html) phases of the data life cycle so that the data and projects the program generates can support the advancement of equity outcomes throughout the state.
:::

The Bioaccumulation Monitoring Program has realized several successes since its inception in 2006, including forming and leading the [Safe to Eat Workgroup](https://mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/), establishing comprehensive and robust bioaccumulation monitoring methodologies, and generating data that is regularly used in the [California Integrated Report process](https://www.waterboards.ca.gov/water_issues/programs/water_quality_assessment/) and to create [Fish Consumption Advisories](https://oehha.ca.gov/fish/advisories) statewide.

In 2020, SWAMP evaluated the Program and determined that, although it has had several successes, to fully align with and achieve its original mission it must address three key issues:

1.  The Program needs to develop and build stronger relationships with California Native American Tribes (tribes) and communities.

2.  Significant data and information gaps remain regarding the question: “Is it safe to eat fish and shellfish from our waters?”, especially for waterbodies or species that are important for subsistence by traditionally underrepresented communities, as well as tribal traditions, culture, and subsistence. 

3.  The Program needs to better collaborate and connect with other Water Boards Divisions, Regions, and programs.

The [Program Realignment](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring/program_realignment.html) process was created to begin to address these issues while balancing and maintaining core aspects of the statewide and regional program efforts, implementing Realignment efforts, and the limited availability of Program and implementation resources. To maintain this balance, the Realignment process was designed to be implemented through a cyclical approach, where a single Realignment cycle consists of a three-year process focused in a single [Water Board Region](https://www.waterboards.ca.gov/waterboards_map.html).

During the three year process, Program, Tribal, community and other government and monitoring partners invest time to meet (via advisory meetings or workshops) to:

-   build relationships and trust among Program, Tribal government and community based organization representatives, as well as with state and federal agency and other monitoring partners

-   learn more about and document Tribal and community monitoring, data, and information needs

-   work with Tribal and community partners to determine how a percentage of the Program's budget will be used to fill priority monitoring, data, and information gaps

For more information see the [Bioaccumulation Monitoring Program Realignment Webpage](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring/program_realignment.html).

### Tribally-centered Training Series

::: callout-note
The [Tribally-centered Training Series](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring/training.html) focuses on improving the [Publish and Share](https://cawaterboarddatacenter.github.io/equity-data-handbook/share.html) phases of the data life cycle so that we can continue to build relationships and trust with our Tribal Government partners, and grow the bioaccumulation monitoring community. All of which will ultimately result in a more equitable Program and the advancement of equity outcomes throughout the state.
:::

The purpose of this training series is to support California Native American Tribes in developing programs in the areas of bioaccumulation monitoring, data analysis, and data use processes, and enable Tribes and other bioaccumulation monitoring groups to adopt those processes into their workflows and more easily partner with the Program and the [Safe to Eat Workgroup](https://mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/index.html).

The training series idea was brought to the program by Tribal partners during early Realignment discussions and the Program decided to invest resources into developing the training series with our Tribal partners as another way the program can operationalize open science and equity principles in the Program.

Key decisions were made with equity in mind:

-   The training series would be co-created with Tribal partners. Course outlines were to be approved by Tribal partners, and slides were to be shared with Tribal partners ahead of each course with enough time for them to review and provide feedback on content.

-   Courses would make time and space for Tribal monitoring experts to share their perspectives and expertise in a way that is comfortable for Tribal contributors. In some cases this meant Tribal experts would lead instruction, in others it meant reserving time for open and tribally-led discussion about topics.

-   All courses would be virtual, less than three hours in length, and free to attend, to increase access to live attendance.

-   Courses would be recorded and posted online after the training, along with training slides, to increase access to content for those that are not able to attend live.

-   Course facilitators would offer to pause the recording during discussion, upon request of an attendee, or to delete discussions sections from recordings before posting. This can help make attendees feel more open to contributing to discussions.

For more information see the [Bioaccumulation Monitoring Program Training Series Webpage](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring/training.html)

## FHAB Program

The mission of the FHAB Program is to support the protection, prevention, and reduction of health risks of algal blooms impacting humans, animals, and the environment. The program coordinates and provides resources for monitoring, response, and research to collect quality data to inform mitigation and management decisions to address drivers of FHABs statewide.  

### Partner Monitoring Program

::: callout-note
The [FHAB Partner Monitoring Program](https://sites.google.com/view/fhab-program-wiki/partner-monitoring?authuser=0) focuses on improving the [Collect and Process](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/) phases of the data life cycle so that *how* we collect data is more equitable.
:::

The FHAB Partner Monitoring Program involves our SWAMP FHAB Program coordinating monitoring with our partners and funding lab analysis for monitoring conducted by partners during the HAB season. Partners can include non-profit organizations, California Tribes, counties, cities, bi-state collaborations, and others.

By covering the costs of our partner's laboratory analyses for regular monitoring during the HAB season, we hope to:

-   build relationships and trust with partners

-   increase coordination among partners so our collective monitoring resources are used more effectively

-   lower financial and logistical barriers for partners to collect data of importance to them

-   increase the amount of quality data that comes in throughout the FHAB season statewide

For more information see the [FHAB Partner Monitoring Program Webpage](https://sites.google.com/view/fhab-program-wiki/partner-monitoring?authuser=0)

### Pre-Holiday Assessments

::: callout-note
The [FHAB Pre-Holiday Assessments](https://sites.google.com/view/fhab-program-wiki/pre-holiday-assessment?authuser=0) focuses on improving the [Collect and Process](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/) phases of the data life cycle so that *how* we collect data is more equitable and protective of public health during high risk times.
:::

Similar to the FHAB Partner Monitoring Program, the FHAB Pre-holiday Assessments involve working with partners to conduct sampling at popular water bodies prior to major holiday weekends, and working with water body managers and the county to determine most appropriate signage to inform visitors of potential HABs.

By leading coordination efforts with our partners, and covering the costs of our partner's laboratory analyses for targeted monitoring before major holiday weekends, we hope to:

-   build relationships and trust with partners and the public

-   increase coordination among partners so our collective monitoring resources are used more effectively

-   lower financial and logistical barriers for partners to collect data of importance to them

-   increase the amount of quality data that comes in before major holiday weekends (i.e., Memorial Day, Independence Day, Labor Day)

-   increase the consistency of communication critical to protect public health

For more information see the [FHAB Pre-Holiday Assessment Webpage](https://sites.google.com/view/fhab-program-wiki/pre-holiday-assessment?authuser=0)

### Training Resources

::: callout-note
The [FHAB Training Resources](https://sites.google.com/view/fhab-program-wiki/home?authuser=0) focus on improving the [Publish and Share](https://cawaterboarddatacenter.github.io/equity-data-handbook/share.html) phases of the data life cycle so that we can continue to build relationships and trust with our partners, and grow the FHAB monitoring community. All of which will ultimately result in a more equitable Program, the advancement of equity outcomes, and protection of public health throughout the state.
:::

With greater than 3,000 lakes, 190,000 river miles, diverse ecosystems ranging from deserts to temperate rain forests, and over 40 million inhabitants, California faces complex monitoring and management issues for FHABs.

The purpose of providing free detailed guidance and training resources online and via live in-person or remote training by SWAMP FHAB Staff, is to make it easier for partners to:

-   build capacity within their own organizations and governments

-   conduct their own high-quality monitoring in areas of interest to them

-   lower barriers to partnership with the FHAB Program

For more information see the [FHAB Program Wiki](https://sites.google.com/view/fhab-program-wiki/home?authuser=0).

## SeMMAP

SeMMAP is exploring how we might use eDNA to augment, complement, and add to other statewide and [regional](https://www.waterboards.ca.gov/water_issues/programs/swamp/monitoring/regional_monitoring_programs/) monitoring programs at the Water Boards, with specific goals including:

-   Explore the use of eDNA in SWAMP monitoring at the Water Boards

-   Build a diverse community of practice in CA

-   Develop Guidance for eDNA monitoring projects

-   Understand how biodiversity data can be used to assess overall ecosystem health and how the biological, physical and anthropogenic environments interact

::: callout-note
The [SWAMP eDNA Metabarcoding Monitoring and Analysis Project](https://experience.arcgis.com/experience/db3a30220d0d4bdea684781cdaef5230/page/Home/) (SeMMAP) has worked on integrating equity into all phases of the data life cycle, with particular focus on the [Plan and Prepare](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/), [Collect and Process](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/), [Assure & Analyze](https://cawaterboarddatacenter.github.io/equity-data-handbook/assure-analyze/), [Preserve & Store](https://cawaterboarddatacenter.github.io/equity-data-handbook/store.html), [Publish and Share](https://cawaterboarddatacenter.github.io/equity-data-handbook/share.html) phases so that the data and data products the project generates can support the advancement of equity outcomes throughout the state.
:::

As SWAMP was developing SeMMAP, key decisions were made with equity in mind, including:

-   Prioritizing engagement and building relationships with our Tribal and community partners

-   Making time to discuss the data sharing and use process, and to address partner concerns around data management, control, and sovereignty

-   Lowering financial and logistical barriers for partners to collect data of importance to them by: paying for kits and analysis, handling kit distribution, leading data management and quality assurance process

-   Sharing data as soon as it's available via an open, accessible, and interactive dashboard that includes a partner project gallery that enables partners to view the data that they collected and share how they are using their eDNA data to advance their water quality monitoring goals

-   Providing free detailed guidance and training resources online to make it easier for partners to:

    -   build capacity within their own organizations and governments
    -   conduct their own high-quality monitoring in areas of interest to them
    -   lower barriers to partnership with SWAMP

## Additional Resources

-   CA Surface Water Ambient Monitoring Programs: Partnering with Tribes for a more open, inclusive, and equitable future. Oct 2024. Anna Holder. [Tribal EPA & U.S. EPA Region 9 Annual Conference](https://tribalepa.com/2024-conference/). [Recording](https://youtu.be/7u4O0VCDGtA?si=wzhp7KDcWBphwtQM).

-   Operationalizing Open Science and Equity in California’s Surface Water Ambient Monitoring Programs. May 2022. Anna Holder. [Joint Aquatic Sciences Meeting](https://jasm2022.aquaticsocieties.org/). [Recording](https://www.youtube.com/watch?v=80HWwyELmMk).
