# Planning

When planning for your data project with an equity lens, it's best to conduct a thorough equity assessment, or scoping process. Equity assessments[^plan-1] are systematic examinations of available data and expert input on how various groups - especially those facing inequity or disparities - are or likely will be affected by a policy, program, or process. They aim to minimize unintended adverse outcomes and maximize opportunities and positive outcomes.

[^plan-1]: The bulk of content on this page has been informed by: [Conducting Intensive Equity Assessments of Existing Programs, Policies, and Processes (hhs.gov)](https://aspe.hhs.gov/sites/default/files/documents/dd148f52c519a5bcc4fde76b4932f53b/Intensive-Equity-Assessment.pdf)

The steps to conducting an equity assessment are described below.

-   [Step 0: Project Scoping](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-0-project-scoping)
-   [Step 1: Describe the selected program, policy, or process, and populations affected by it](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-1-describe-the-selected-program-policy-or-process-and-populations-affected-by-it)
-   [Step 2. Consider historical, societal, and policy context and drivers of disparities](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-2.-consider-historical-societal-and-policy-context-and-drivers-of-disparities)
-   [Step 3. Collect expert input, including from affected community members](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-3.-collect-expert-input-including-from-affected-community-members)
-   [Step 4. Identify information sources and gaps](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-4.-identify-information-sources-and-gaps)
-   [Step 5. Analyze program/policy effects - potential or current - on people and communities](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-5.-analyze-programpolicy-effects---potential-or-current---on-people-and-communities)
-   [Step 6. Plan for action and accountability](https://cawaterboarddatacenter.github.io/equity-data-handbook/plan-prep/plan.html#step-6.-plan-for-action-and-accountability)

Although these steps are numbered for clarity, teams should synthesize information from all steps rather than completing them in isolation or one at a time.

## Step 0: Project Scoping

**Time frame and level of effort:**

-   Plan a detailed schedule that accounts for staff availability, budget, technical assistance needs, data availability, and the need to make decisions in a particular time frame.

-   Identify and document risks to the timeline, such as staff availability, or threats to the comprehensiveness of the assessment, such as lack of access to experts. Consider potential ways to mitigate risks.

**Project team:**

-   Define roles for team members and assign responsibilities. Plan to share information at key milestones to synthesize information from different assessment steps.

-   Consider how to meaningfully involve experts, including people with lived experience with relevant programs and topics; people in communities affected by the program, policy, or process; staff who work with program participants/beneficiaries; or representatives of other offices. Experts can contribute to the assessment process in several ways, such as suggesting data sources, providing multiple perspectives to inform and enhance the analysis, and developing recommendations for action.

## Step 1: Describe the selected program, policy, or process, and populations affected by it

Describe the focus of the assessment to provide a foundation for all members of the assessment team and external partners.

-   What is the purpose of the selected program, policy, or process, and what are its goals?

-   What are the known successes or challenges in meeting those goals?

-   What types of actions or policy levers are involved in the selected program, policy, or process (such as grants, contracts, waivers, guidance to partners, technical assistance, or other actions)?

-   Which of these actions will be included in the assessment?

-   What general descriptive or performance data can the organization use to describe the program, policy, or process (such as number served, total funds distributed, uptake estimates, or other key outcomes)?

-   Are there existing quantifiable performance targets relevant to the focus of the assessment? Provide a brief summary.

Identify and describe populations of interest

-   What populations are participating in the program, policy, or process, including program participants/beneficiaries? Consider which characteristics are relevant and of interest, such as race, ethnicity, gender identity, sexual orientation, disability status, income, religion, and rural geography.

-   What populations are currently left out, or not participating or benefiting at desired rates or at the same rates as others? What are other disparities related to the selected program, policy, or process that are known at the outset of the assessment?

-   What are the information sources for those inequities or disparities?  What is the comparison population or reference point for observed disparities? Reference point options include the total population in an area, the national population, the largest group, or a benchmark chosen through a planning process. Whenever possible, try to think critically about this population rather than simply defaulting to comparison populations used in the past.

-   How might population groups’ identifying characteristics overlap in ways that expose them to relatively greater inequities (known as intersectionality)? What implications does this overlap have for the impacts of the program, policy or process? For example, immigrants who are also LGBTQIA+ might face multiple barriers in accessing a particular program.

::: callout-tip
Many local city and county governments have compiled their own resources for working with equity data, like Oakland's [Geographic Equity Toolbox](https://www.oaklandca.gov/resources/oakdot-geographic-equity-toolbox), Portland's [Racial Equity Toolkit](https://www.portlandoregon.gov/oehr/71685), and New York City's interactive equity data tool [EquityNYC](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequity.nyc.gov%2F&data=05%7C01%7Cnicholas.martorano%40waterboards.ca.gov%7C87a614b2e3db4c85368c08dbc55a8595%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638320764855634179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r%2Br4%2BybTh130ovhG12PjYHQYqVHlz4jSB8gXj3KTnAI%3D&reserved=0), including a [Mapping Equity tool](https://equity.nyc.gov/mapping-equity). Before starting your project, it is a good idea to do some research online to identify pre-existing resources available in your region.
:::

## Step 2. Consider historical, societal, and policy context and drivers of disparities

Describe the context for observed disparities and the program or policy itself.

-   What is the social and cultural history of the populations listed in Step 1 and how does this history shape their current conditions? How does this context play a role in how these populations might perceive, access, or otherwise interact with the program or policy?

-   What structural or social drivers of disparities might explain observed disparities? Structural drivers of disparities are governing processes and economic and social policies that distribute power and resources in unfair ways, such as an inequitable distribution of emergency funds to certain communities. Social drivers of disparities are differences in the conditions in which people are born, grow, live, work, and age, such as poverty, employment, housing, environment quality, transportation, food security, and community safety. Differences in these social conditions drive disparities. Although these conditions are also known as social determinants of health, this tool uses a broader term to encompass multiple outcomes, including both health outcomes and other outcomes (e.g., economic outcomes). Thinking through these drivers of disparities is important for placing focus on systems and institutions that need to be changed, and it helps to avoid blaming groups of people for poor outcomes.

-   What is known about whether structural, systemic, or institutional racism or structural barriers affect the implementation and outcomes of previous programs or policies? Systemic or institutional racism refers to policies and practices that create or sustain disparate outcomes for persons of different races. An example is redlining, where financial services and other housing-related opportunities were restricted for individuals largely based on their race/ethnicity and originating neighborhoods (see this 2021 Memorandum for the Secretary of Housing and Urban Development regarding [Redressing Our Nation's and the Federal Government's History of Discriminatory Housing Practices and Policies](https://www.federalregister.gov/documents/2021/01/29/2021-02074/redressing-our-nations-and-the-federal-governments-history-of-discriminatory-housing-practices-and))

## Step 3. Collect expert input, including from affected community members

Experts can include former or current program participants/beneficiaries, members of communities affected by the program, policy, or process, staff who work with program participants/beneficiaries or affected communities, subject matter experts such as researchers, or staff in other organizations, among others. Sources of expert input on programs, policies, and processes include listening sessions, surveys, interviews, focus groups, and position papers by experts in the field or advocacy groups.

-   How will the assessment team engage experts with lived experience with relevant programs, policies, processes, and/or issues? To what extent can these experts be part of the assessment team?

-   How will the assessment team engage other experts in the equity assessment (in addition to potentially involving them in the assessment team)? Which experts will be engaged?

-   What individuals or communities have historically been excluded or disempowered in decision making? How can they be included and meaningfully engaged?

-   How can the assessment team ensure inclusivity when engaging experts, such as translation services or accommodations for people with disabilities? Will there be different options for sharing input for people with different communication preferences or time or transportation constraints?

-   How will the assessment team work to decrease power dynamics and ensure that experts are comfortable providing candid input? How can the team be transparent about how input will be shared and used?

-   What methods can the assessment team use to collect input, such as focus groups on participants/beneficiaries’ experiences with programs? What are experts’ experiences with current programs and policies, and what are their views on the benefits and burdens involved in participating?

-   What are experts’ perceptions about barriers to participation? Can experts help the assessment team understand whether there are current or potential burdens or barriers that are more severe for certain population groups?

::: callout-tip
For more detailed guidance and resources regarding outreach and engagement, see the [Practical Guidance Document](https://cawaterboards.sharepoint.com/:b:/r/sites/OPP/WBCollab/OPP%20Resource%20Pages%20Content/a_Public%20Engagement/Equitable%20Engagement%20Guidance/Advancing%20Equity%20Guidance_OPP_02102023.pdf?csf=1&web=1&e=ux6gtX) developed by the Office of Public Participation.
:::

## Step 4. Identify information sources and gaps

Consider a variety of qualitative and quantitative information sources to support the assessment, including gray and peer-reviewed literature, organization documents and administrative records, surveys, customer inquiry or complaint information, administrative data, program performance data, key informant interviews, and listening sessions or focus groups. Ideally, equity assessments often include both qualitative and quantitative data. Data sources can include, but should not be limited to, expert views.

-   What are the quantitative data sources for the assessment process? Quantitative data such as program, administrative, or survey data shed light on the magnitude and prevalence of an inequity or an opportunity for improvement.

-   Are available quantitative data disaggregated by relevant variables, such as race, ethnicity, income, and relevant geographic areas? If not, how can the assessment incorporate data that can help organizations understand or estimate the equity impacts of the program, policy, or process?

-   What are the qualitative data sources for the assessment process? Qualitative data such as interview or focus group data increase understanding of context, as well as helping to interpret and understand quantitative data.

-   Are there gaps or limitations in the information needed for the assessment? If either qualitative or quantitative data are not available, explain why. If there are gaps, how might the assessment team obtain new or better information, or highlight the need for investments in better data? It is important to describe gaps that might reflect historically overlooked inequities or point to the need for information sources that could be developed in future years.

## Step 5. Analyze program/policy effects - potential or current - on people and communities

Drawing on all previous steps in the assessment process, analyze the available data and describe equity-related outcomes of the program, policy, or process. Describe findings with as much specificity as possible.

-   What quantitative and qualitative analysis methods did the team use to analyze the available data? Did the team synthesize quantitative and qualitative data to develop a complete picture of current inequities or disparities related to the program, policy, or process?

-   What are the assessment team’s findings on positive and negative equity-related outcomes of the program, policy, or process? What quantitative and qualitative evidence of inequities exists?

-   What evidence is there of inequities in areas such as awareness of programs and benefits, processes and rules, administrative burden, access to services, participation, outcomes, quality, and engagement?

-   How do findings change the team’s understanding of disparities related to the selected program, policy, or process known at the outset of the assessment?

-   What factors might be driving observed inequities or disparities? Are any of those factors potentially caused by the program or policy that is the focus of the assessment?

-   Have experts helped the assessment team interpret the available data or validate or refine the initial findings?

-   In what ways might the findings be limited due to data gaps or analysis constraints? What findings point to the need for further research?

## Step 6. Plan for action and accountability

Develop a detailed plan to address inequities identified in Step 5 within the scope of your program.

-   What solutions are needed to resolve observed inequities or disparities, or to address identified drivers of those inequities or disparities? Which solutions are in the program’s sphere of authority?

-   What are the program’s short-term and long-term goals for improvement? Quantify those goals if possible.

-   What steps will the program take to accomplish each goal? What coordination, training, information systems changes, business process changes, or other implementation actions are needed?

-   Have subject matter experts—including those with lived experience—weighed in on needed solutions, proposed goals, or planned action steps? Are all components of the improvement plan responsive to the needs and cultures of different populations or communities?

-   What resources will the program need to carry out the improvement plan?

-   Has the program consulted or collaborated with key partners on potential improvement options and actions?

-   In what ways could the program coordinate with other partners to achieve equity improvements that are not solely within the control or influence of the program conducting the assessment?

Additional follow-up actions help programs learn about equity impacts and whether implementation should be adjusted to realize positive outcomes. In addition, equity assessments have the potential to generate many new lessons about equity that could be helpful for other partners. Articulating plans for these actions is part of the equity assessment even though these actions occur after the formal assessment is over.

-   Would sharing the equity assessment with other partners support collaboration on other policies and programs intended to benefit priority populations?

-   Would sharing the equity assessment or a summary of findings with experts who were not directly involved in the assessment further promote equity through transparency and accountability?

-   What measures or indicators will the program use to track progress over time? Are these disaggregated individual-level or community-level measures? Monitoring can help the program assess whether patterns or trends are in the expected direction or require course corrections.

-   How and when will the organization evaluate the results of potential program changes? Evaluations focus on whether programs or policies reach their goals within a defined period. How can the organization design an equitable and inclusive evaluation?

-   Who will be responsible for developing and executing monitoring and evaluation plans?  

-   Will the program share monitoring and evaluation results with the experts involved in the assessment or other partners? If so, how?
